"""Esquema inicial: las once entidades del modelo de datos.

`TASK-01` y `TASK-02` del Sprint 3. Crea las extensiones que exige el modelo
—PostGIS para las columnas `GEOGRAPHY`— y las tablas de `docs/data-model.md`.

Los índices GiST sobre las columnas geográficas **no se declaran aquí**:
GeoAlchemy2 los emite junto con el `CREATE TABLE`. Declararlos otra vez haría
fallar la migración con «relation already exists».

Revision ID: 0001_esquema_inicial
Create Date: 2026-09-07
"""

from __future__ import annotations

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = "0001_esquema_inicial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # TASK-02: sin PostGIS las columnas GEOGRAPHY no se pueden crear.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elementos_rastreados',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_tracking_externo', sa.String(length=20), nullable=False),
    sa.Column('tracking_externo', sa.String(length=50), nullable=False),
    sa.Column('via_transporte', sa.String(length=10), nullable=False),
    sa.Column('eta_api', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ata_api', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posicion_actual', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('velocidad_actual', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ultima_actualizacion_api', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_tracking_externo IN ('MMSI', 'IMO', 'BUQUE', 'VUELO', 'CONTENEDOR', 'BL', 'BOOKING', 'MAWB')", name=op.f('ck_elementos_rastreados_tipo_tracking')),
    sa.CheckConstraint("via_transporte IN ('AEREO', 'MARITIMO', 'TERRESTRE')", name=op.f('ck_elementos_rastreados_via_transporte')),
    sa.CheckConstraint('velocidad_actual IS NULL OR velocidad_actual >= 0', name=op.f('ck_elementos_rastreados_velocidad')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elementos_rastreados')),
    comment='Nave, vuelo o contenedor objeto de seguimiento.'
    )
    op.create_index('uq_elementos_rastreados_natural_activo', 'elementos_rastreados', ['tipo_tracking_externo', 'tracking_externo'], unique=True, postgresql_where=sa.text('activo'))
    op.create_table('maestro_destinos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('via_transporte', sa.String(length=10), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('radio_geocerca_km', sa.Integer(), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pais ~ '^[A-Z]{2}$'", name=op.f('ck_maestro_destinos_pais')),
    sa.CheckConstraint("via_transporte IN ('AEREO', 'MARITIMO', 'TERRESTRE')", name=op.f('ck_maestro_destinos_via_transporte')),
    sa.CheckConstraint('lead_time_dias >= 0', name=op.f('ck_maestro_destinos_lead_time')),
    sa.CheckConstraint('radio_geocerca_km IS NULL OR radio_geocerca_km > 0', name=op.f('ck_maestro_destinos_radio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maestro_destinos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_maestro_destinos_codigo')),
    comment='Puertos y aeropuertos de entrada (TASK-13, repuesto en TASK-31).'
    )
    op.create_table('maestro_paises',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("codigo ~ '^[A-Z]{2}$'", name=op.f('ck_maestro_paises_codigo_iso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maestro_paises')),
    sa.UniqueConstraint('codigo', name=op.f('uq_maestro_paises_codigo')),
    comment='Catálogo de países de origen (TASK-29). ISO 3166-1 alfa-2.'
    )
    op.create_table('materiales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('unidad_medida', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiales')),
    sa.UniqueConstraint('codigo', name=op.f('uq_materiales_codigo')),
    comment='Maestro de materiales, normalizado desde el código de origen.'
    )
    op.create_table('proveedores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pais IS NULL OR pais ~ '^[A-Z]{2}$'", name=op.f('ck_proveedores_pais')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores')),
    sa.UniqueConstraint('codigo', name=op.f('uq_proveedores_codigo')),
    comment='Maestro de proveedores, normalizado desde el código de origen.'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('COMPRAS', 'LOGISTICA', 'PLANIFICACION', 'ADMINISTRADOR')", name=op.f('ck_usuarios_rol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('correo', name=op.f('uq_usuarios_correo')),
    sa.UniqueConstraint('usuario', name=op.f('uq_usuarios_usuario')),
    comment='Usuarios con credencial propia. Sin SSO ni Active Directory.'
    )
    op.create_table('alias_paises',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_pais', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['maestro_paises.id'], name=op.f('fk_alias_paises_id_pais_maestro_paises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alias_paises')),
    sa.UniqueConstraint('alias', name=op.f('uq_alias_paises_alias')),
    comment='Grafías alternativas del país en el archivo de origen (TASK-29).'
    )
    op.create_index(op.f('ix_alias_paises_id_pais'), 'alias_paises', ['id_pais'], unique=False)
    op.create_table('historial_tracking',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_elemento_rastreado', sa.BigInteger(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posicion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('velocidad', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rumbo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado_api', sa.String(length=40), nullable=True),
    sa.Column('payload_api', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.CheckConstraint('rumbo IS NULL OR (rumbo >= 0 AND rumbo < 360)', name=op.f('ck_historial_tracking_rumbo')),
    sa.CheckConstraint('velocidad IS NULL OR velocidad >= 0', name=op.f('ck_historial_tracking_velocidad')),
    sa.ForeignKeyConstraint(['id_elemento_rastreado'], ['elementos_rastreados.id'], name=op.f('fk_historial_tracking_id_elemento_rastreado_elementos_rastreados'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_tracking')),
    comment='Bitácora inmutable de posiciones. No se actualiza ni se borra.'
    )
    op.create_index('ix_historial_tracking_elemento_fecha', 'historial_tracking', ['id_elemento_rastreado', 'fecha_registro'], unique=False)
    op.create_index('uq_historial_tracking_lectura', 'historial_tracking', ['id_elemento_rastreado', 'fecha_registro'], unique=True)
    op.create_table('parametros_sistema',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo_dato', sa.String(length=15), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('id_usuario_modificacion', sa.BigInteger(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_dato IN ('ENTERO', 'DECIMAL', 'BOOLEANO', 'TEXTO')", name=op.f('ck_parametros_sistema_tipo_dato')),
    sa.ForeignKeyConstraint(['id_usuario_modificacion'], ['usuarios.id'], name=op.f('fk_parametros_sistema_id_usuario_modificacion_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('clave', name=op.f('pk_parametros_sistema')),
    comment='Umbrales y frecuencias ajustables sin tocar el código.'
    )
    op.create_table('pedidos_transito',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('oc_numero', sa.String(length=20), nullable=False),
    sa.Column('posicion_oc', sa.Integer(), nullable=False),
    sa.Column('tracking_interno', sa.String(length=30), nullable=False),
    sa.Column('id_proveedor', sa.BigInteger(), nullable=False),
    sa.Column('id_material', sa.BigInteger(), nullable=False),
    sa.Column('id_destino', sa.BigInteger(), nullable=False),
    sa.Column('id_pais_origen', sa.BigInteger(), nullable=True),
    sa.Column('via_transporte', sa.String(length=10), nullable=False),
    sa.Column('cantidad_pedida', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unidad_medida', sa.String(length=10), nullable=False),
    sa.Column('fecha_entrega_pedido', sa.Date(), nullable=False),
    sa.Column('incoterm', sa.String(length=15), nullable=True),
    sa.Column('temperatura', sa.String(length=40), nullable=True),
    sa.Column('tipo_proveedor', sa.String(length=15), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('id_elemento_rastreado', sa.BigInteger(), nullable=True),
    sa.Column('lead_time_destino_dias', sa.Integer(), nullable=False),
    sa.Column('ajuste_manual_dias', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('eta_utilizada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ata_confirmada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ata_inferida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_proyectada_disponible', sa.Date(), nullable=True),
    sa.Column('fecha_ultimo_recalculo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etapa_viaje', sa.String(length=20), nullable=False),
    sa.Column('estado_cumplimiento', sa.String(length=20), nullable=True),
    sa.Column('estado_calculado', sa.String(length=20), nullable=False),
    sa.Column('fecha_recepcion_planta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cantidad_recibida', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('motivo_cierre', sa.String(length=25), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(id_elemento_rastreado IS NULL) = (etapa_viaje = 'SIN_TRACKING')", name=op.f('ck_pedidos_transito_sin_tracking')),
    sa.CheckConstraint("(motivo_cierre IS NULL) = (estado_calculado NOT IN ('CERRADO','CANCELADO'))", name=op.f('ck_pedidos_transito_terminal')),
    sa.CheckConstraint("estado_calculado IN ('SIN_TRACKING', 'EN_ORIGEN', 'EN_TRANSITO', 'EN_DESTINO', 'EN_PROCESO_ADUANAL', 'RECIBIDO_EN_PLANTA', 'A_TIEMPO', 'EN_RIESGO', 'RETRASADO', 'CERRADO', 'CANCELADO')", name=op.f('ck_pedidos_transito_estado_calculado')),
    sa.CheckConstraint("estado_cumplimiento IS NULL OR estado_cumplimiento IN ('A_TIEMPO', 'EN_RIESGO', 'RETRASADO')", name=op.f('ck_pedidos_transito_estado_cumplimiento')),
    sa.CheckConstraint("etapa_viaje IN ('SIN_TRACKING', 'EN_ORIGEN', 'EN_TRANSITO', 'EN_DESTINO', 'EN_PROCESO_ADUANAL', 'RECIBIDO_EN_PLANTA')", name=op.f('ck_pedidos_transito_etapa_viaje')),
    sa.CheckConstraint("motivo_cierre <> 'RECEPCION_CONFORME' OR (fecha_recepcion_planta IS NOT NULL AND cantidad_recibida IS NOT NULL)", name=op.f('ck_pedidos_transito_recepcion')),
    sa.CheckConstraint("motivo_cierre IS NULL OR motivo_cierre IN ('RECEPCION_CONFORME', 'CIERRE_FORZADO', 'CANCELACION')", name=op.f('ck_pedidos_transito_motivo_cierre')),
    sa.CheckConstraint("tipo_proveedor IS NULL OR tipo_proveedor IN ('LOCAL', 'INTERNACIONAL')", name=op.f('ck_pedidos_transito_tipo_proveedor')),
    sa.CheckConstraint("via_transporte IN ('AEREO', 'MARITIMO', 'TERRESTRE')", name=op.f('ck_pedidos_transito_via_transporte')),
    sa.CheckConstraint('cantidad_pedida > 0', name=op.f('ck_pedidos_transito_cantidad_pedida')),
    sa.CheckConstraint('cantidad_recibida IS NULL OR cantidad_recibida >= 0', name=op.f('ck_pedidos_transito_cantidad_recibida')),
    sa.CheckConstraint('lead_time_destino_dias >= 0', name=op.f('ck_pedidos_transito_lead_time')),
    sa.CheckConstraint('posicion_oc > 0', name=op.f('ck_pedidos_transito_posicion_oc')),
    sa.ForeignKeyConstraint(['id_destino'], ['maestro_destinos.id'], name=op.f('fk_pedidos_transito_id_destino_maestro_destinos')),
    sa.ForeignKeyConstraint(['id_elemento_rastreado'], ['elementos_rastreados.id'], name=op.f('fk_pedidos_transito_id_elemento_rastreado_elementos_rastreados')),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id'], name=op.f('fk_pedidos_transito_id_material_materiales')),
    sa.ForeignKeyConstraint(['id_pais_origen'], ['maestro_paises.id'], name=op.f('fk_pedidos_transito_id_pais_origen_maestro_paises')),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], name=op.f('fk_pedidos_transito_id_proveedor_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos_transito')),
    sa.UniqueConstraint('oc_numero', 'posicion_oc', name='oc_numero'),
    sa.UniqueConstraint('tracking_interno', name=op.f('uq_pedidos_transito_tracking_interno')),
    comment='Línea de orden de compra en tránsito. Granularidad: la línea.'
    )
    op.create_index('ix_pedidos_transito_estado_calculado', 'pedidos_transito', ['estado_calculado'], unique=False)
    op.create_index('ix_pedidos_transito_fecha_proyectada', 'pedidos_transito', ['fecha_proyectada_disponible'], unique=False)
    op.create_index(op.f('ix_pedidos_transito_id_destino'), 'pedidos_transito', ['id_destino'], unique=False)
    op.create_index(op.f('ix_pedidos_transito_id_elemento_rastreado'), 'pedidos_transito', ['id_elemento_rastreado'], unique=False)
    op.create_index(op.f('ix_pedidos_transito_id_material'), 'pedidos_transito', ['id_material'], unique=False)
    op.create_index(op.f('ix_pedidos_transito_id_pais_origen'), 'pedidos_transito', ['id_pais_origen'], unique=False)
    op.create_index(op.f('ix_pedidos_transito_id_proveedor'), 'pedidos_transito', ['id_proveedor'], unique=False)
    op.create_index('ix_pedidos_transito_oc_numero', 'pedidos_transito', ['oc_numero'], unique=False)
    op.create_table('auditoria_intervenciones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_intervencion', sa.String(length=30), nullable=False),
    sa.Column('campo_afectado', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.CheckConstraint("tipo_intervencion IN ('CONFIRMACION_DESEMBARCO', 'PASO_A_ADUANAL', 'RECEPCION_PLANTA', 'LIBERACION_CALIDAD', 'TRANSBORDO', 'AJUSTE_MANUAL', 'CIERRE_FORZADO', 'ASOCIACION_TRACKING')", name=op.f('ck_auditoria_intervenciones_tipo_intervencion')),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos_transito.id'], name=op.f('fk_auditoria_intervenciones_id_pedido_pedidos_transito'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_auditoria_intervenciones_id_usuario_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria_intervenciones')),
    comment='Bitácora de intervenciones manuales exigida por RF-14.'
    )
    op.create_index(op.f('ix_auditoria_intervenciones_id_usuario'), 'auditoria_intervenciones', ['id_usuario'], unique=False)
    op.create_index('ix_auditoria_intervenciones_pedido_fecha', 'auditoria_intervenciones', ['id_pedido', 'fecha_hora'], unique=False)
    op.create_table('pedido_elemento_rastreado',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('id_elemento_rastreado', sa.BigInteger(), nullable=False),
    sa.Column('tramo', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('puerto_transbordo', sa.String(length=80), nullable=True),
    sa.Column('fecha_notificacion', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.CheckConstraint('fecha_hasta IS NULL OR fecha_hasta >= fecha_desde', name=op.f('ck_pedido_elemento_rastreado_rango')),
    sa.CheckConstraint('tramo > 0', name=op.f('ck_pedido_elemento_rastreado_tramo_positivo')),
    sa.ForeignKeyConstraint(['id_elemento_rastreado'], ['elementos_rastreados.id'], name=op.f('fk_pedido_elemento_rastreado_id_elemento_rastreado_elementos_rastreados'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos_transito.id'], name=op.f('fk_pedido_elemento_rastreado_id_pedido_pedidos_transito'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido_elemento_rastreado')),
    sa.UniqueConstraint('id_pedido', 'tramo', name='tramo'),
    comment='Tramos de un pedido: 1 el original, +1 por cada transbordo.'
    )
    op.create_index(op.f('ix_pedido_elemento_rastreado_id_elemento_rastreado'), 'pedido_elemento_rastreado', ['id_elemento_rastreado'], unique=False)
    op.create_index(op.f('ix_pedido_elemento_rastreado_id_pedido'), 'pedido_elemento_rastreado', ['id_pedido'], unique=False)
    op.create_index('uq_pedido_elemento_rastreado_vigente', 'pedido_elemento_rastreado', ['id_pedido'], unique=True, postgresql_where=sa.text('fecha_hasta IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('pedido_elemento_rastreado')
    op.drop_table('auditoria_intervenciones')
    op.drop_table('pedidos_transito')
    op.drop_table('parametros_sistema')
    op.drop_table('historial_tracking')
    op.drop_table('alias_paises')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('materiales')
    op.drop_table('maestro_paises')
    op.drop_table('maestro_destinos')
    op.drop_table('elementos_rastreados')
    # Las extensiones no se eliminan: pueden estar en uso por otros esquemas.
